project:
  type: website
  output-dir: docs

website:
  title: "New Worlds Reading Initiative Data Team"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Reports
        menu:
          - href: reports/Eligiblity_table_2526/Eligibility_table.qmd
            text: Eligibility Table

format:
  html:
    theme: mintly
    css: styles.css
