project:
  output-dir: docs

    
website:
  title: "New Worlds Reading Initiative Data Team"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: flatly
    css: styles.css