project:
  type: website
  output-dir: docs

website:
  title: "<span>Data</span><br><span>Team</span>"
  navbar:
    logo: reports/Eligiblity_table_2526/images/NWRI_Logo_blue_orange.png
    left:
      - href: index.qmd
        text: Home
      - text: Reports
        menu:
          - href: reports/Eligiblity_table_2526/Eligibility_table.qmd
            text: Eligibility Table
          - href: reports/heatmap_districts/Heat_map_enroll.qmd
            text: Enrollment Tables
            
format:
  html:
    theme: mintly
    css: styles.css
