---
title: "New Worlds Reading Initiative Data Team"
format: html
---

# Welcome 👋

This is the landing page for our data products.

## Tables

### General:

-   [📊 Eligibility & Enrollment Table 2025-26](reports/Eligiblity_table_2526/Eligibility_table.html)
-   [📊 Enrollment Table 2025-26](reports/heatmap_districts/Heat_map_enroll.html)


## Reports

### General:

-   [📈 School Level Analyses 2024-25](reports/School_level_report_2425/School_Level_Report.html)

### 📘 E Team:

-   [📑 Engagement Family Quarterly Survey Reports 2024-25](engagement_quarters.html)
-   [📑 District POC Annual Survey Report 2024-25](reports/District_POC_survey_report_2425/District_POC_Annual_Report_2425.html)

### G Team:

-   [📑 Regional Partners Family Quarterly Survey Reports 2024-25](regional_quarters.html)
-   [📑 Regional Partner Annual Survey Report 2024-25](reports/Regional_Partner_annual_survey_report_2425/Regional_Partner_Annual_Report_2425.html)

## Misc:

-   [📊 GRAPH! Work in Progress](graphingtrial.html)
