---
title: "<span style='font-family:Poppins, sans-serif; font-size:18px; font-style:italic;'>Enrollment activity (Last updated: `r format(Sys.time(), '%B %d, %Y %I:%M %p', tz = 'America/New_York')`)"
author: "NWRI D Team"
output-dir: ../../docs/
format:
  html:
    self-contained: true
    toc: false
    page-layout: custom
    css: styles.css
editor: visual
execute:
  echo: false
  cache: false
  freeze: false
---

```{=html}
<script>
  const password = prompt("Enter password");
  if (password !== "NWRI") {
    document.body.innerHTML = "Access denied";
  }
</script>
```

```{r setup, include=FALSE}

library(dplyr)
library(ggplot2)
library(tidyr)
require(reactable)
require(reactablefmtr)
library(stringr)
require(htmltools)
library(wesanderson)


```

```{r, echo=FALSE, include=FALSE, warning=FALSE, cache=FALSE}
# Function to get latest RDS based on filename date
get_latest_rds <- function(dir_path, verbose = TRUE) {
  rds_files <- list.files(path = dir_path, pattern = "\\.rds$", full.names = TRUE)
  
  if (length(rds_files) == 0) {
    if (verbose) cat("No .rds files found in", dir_path, "\n")
    return(NULL)
  }
  
  file_dates <- sub(".*?(\\d{4}-\\d{2}-\\d{1,2})\\.rds$", "\\1", basename(rds_files))
  file_dates <- as.Date(file_dates, format = "%Y-%m-%d")
  
  latest_file <- rds_files[which.max(file_dates)]
  
  if (verbose) cat("Loaded file from:", latest_file, "\n")
  readRDS(latest_file)
}


total_data<-get_latest_rds("data/total_data")
diff_total<-get_latest_rds("data/diff_total")
```

```{r, echo=FALSE, include=FALSE, warning=FALSE, cache=FALSE}
d = total_data
base_plot <- ggplot(data = NULL) +
      geom_rect(aes(xmin = 8,xmax = 14, ymin = -Inf, ymax = Inf),
                fill = "grey", alpha = 0.2) +
      annotate("text", x = 11, y = 400000, label = "PM1", size = 9) +
      geom_rect(aes(xmin = 25,xmax = 31, ymin = -Inf, ymax = Inf),
                fill = "grey", alpha = 0.2) +
      annotate("text", x = 28, y = 400000, label = "PM2", size = 9) +
      geom_rect(aes(xmin = 44,xmax = 49, ymin = -Inf, ymax = Inf),
                fill = "grey", alpha = 0.2) +
      annotate("text", x = 46.5, y = 400000, label = "PM3", size = 9) +
      geom_line(data = d,
                aes(x = week_of_cycle, y = cumulative_n_includingold,
                    color = Year), linewidth = 1) +
      geom_point(data = d,
                 aes(x = week_of_cycle, y = cumulative_n_includingold,
                     fill = Year), size = 2, pch = 21, color = "white") +
      labs(title = "Enrollment Over Time", x = "Weeks", y = "Enrollment") +
      scale_colour_discrete(c("red","blue", "orange")) +
      scale_colour_manual(values = c("#1B9E77", "#D95F02", "#7570B3")) +
      scale_fill_manual(values = c("#1B9E77", "#D95F02", "#7570B3"))+
      theme_minimal() +
      theme(axis.title = element_text(size = 16),
            axis.text = element_text(size = 14),
            legend.text = element_text(size = 16),
            legend.title = element_blank())


diff_total <- diff_total$`cumulative_applicants_Current Year` - diff_total$`cumulative_applicants_Previous Year`

directioncum <- ifelse(diff_total >= 0, "ahead", "behind")
color <- ifelse(diff_total >= 0, "green" , "red")
```

:::: panel-tabset
## Enrollment Trends

::: {style="font-size: 28px;"}
We are currently [ `r formatC(abs(diff_total), format = "f", big.mark = ",", digits = 0)` enrollees `r directioncum` ]{style="color:`r color`; font-weight:bold;"} compared to the same time last year.
:::

```{r, echo=FALSE, include=TRUE, warning=FALSE, cache=FALSE, message=FALSE, fig.align='center',fig.width=16, fig.height=7, out.width="100%"}
base_plot
```

## Other plot here

```{r, echo=FALSE, include=FALSE, warning=FALSE, cache=FALSE}
graph_total = total_data %>%
   filter(! Year == "Goal")
other_plot<-ggplot(data = NULL) +
      geom_rect(aes(xmin = 8,xmax = 14, ymin = -Inf, ymax = Inf),
                fill = "grey", 
                alpha = 0.2) +
      annotate("text", x = 11, y = 90000, label = "PM1", size = 9) +
      geom_rect(aes(xmin = 25,xmax = 31, ymin = -Inf, ymax = Inf),
                fill = "grey", 
                alpha = 0.2) +
      annotate("text", x = 28, y = 90000, label = "PM2", size = 9) +
      geom_rect(aes(xmin = 44,xmax = 49, ymin = -Inf, ymax = Inf),
                fill = "grey", alpha = 0.2) +
      annotate("text", x = 46.5, y = 90000, label = "PM3", size = 9) +
      geom_area(data = graph_total,
                aes(x = week_of_cycle, y = cumulative_applicants, fill = Year),
                position = "identity", 
                alpha = 0.8) +
      labs(title = "Enrollment Over Time", x = "Weeks", y = "Enrollment") +
      theme_minimal() +
      theme(axis.title = element_text(size = 16),
            axis.text = element_text(size = 14))

```

```{r, echo=FALSE, include=TRUE, warning=FALSE, cache=FALSE, message=FALSE, fig.align='center',fig.width=16, fig.height=7, out.width="100%"}
other_plot
```

## PM1 Progress 2025-26

```{r, echo=FALSE, include=TRUE, warning=FALSE, cache=FALSE, message=FALSE, fig.align='center',fig.width=16, fig.height=7, out.width="100%"}
#read in eligiblity and enrollment data



prepm1<-read.csv("data/dropbox/enrollments_20250813.csv", na.strings = c("NA", ""))
postpm1<-read.csv("data/dropbox/enrollments_20251118.csv", na.strings = c("NA", ""))
data_list<-list(prepm1, postpm1)


enrolled_students <- postpm1 %>%
    group_by(DistrictID, SchoolID, Grade) %>%
    summarise(n_enrolled = n(), .groups = "drop")

nwri_all_prepm1<-readRDS("data/base_data/nwri_all_table_08112025.rds")
nwri_all_postpm1<-readRDS("data/base_data/nwri_all_table_11172025.rds")

all_students_list<-list(nwri_all_prepm1, nwri_all_postpm1)


nwri_eligibleprepm1<-readRDS("data/base_data/nwri_eligible_table_08112025.rds")
nwri_eligiblepostpm1<-readRDS("data/base_data/nwri_eligible_table_11172025.rds")

eligiblity_list<-list(nwri_eligibleprepm1, nwri_eligiblepostpm1)

MSID<-readRDS("data/base_data/MSID_10072025.rds")



lost_kids<-lapply(data_list, function(x){
    # ---- CLEAN ENROLLED ----
nwri_enrolled <- x %>%
  mutate(across(where(is.character), str_squish))

# ---- LOST KIDS ----
lost_kids <- nwri_enrolled %>%
  filter(is.na(MappedDOESchool)) %>%
  mutate(DistrictName = str_to_upper(DistrictName)) %>%
  mutate(DistrictName = case_when(
    DistrictName == "MIAMI DADE" ~ "MIAMI-DADE",
    DistrictName == "FLORIDA SCHOOL FOR THE DEAF & BLIND" ~ "DEAF/BLIND",
    DistrictName == "VIRTUAL SCHOOL" ~ "FL VIRTUAL",
    DistrictName == "UF LAB SCHOOL" ~ "UF LAB SCH",
    DistrictName %in% c("IDEA", "IDEA PUBLIC SCHOOLS") ~ "IDEA PUB SCH",
    DistrictName == "FSU LAB SCHOOL" ~ "FSU LAB SCH",
    DistrictName %in% c("UCP", "KIPP", "MATER") ~ NA,
    DistrictName == "FAU LAB SCHOOL" ~ "FAU LAB SCH",
    DistrictName == "SAN JOSE CHARTER" ~ "DUVAL",
    DistrictName == "FAMU LAB SCHOOL" ~ "FAMU LAB SCH",
    TRUE ~ DistrictName
  ))

# ---- LOST KIDS SUMMARY ----
lost_kids_data <- lost_kids %>%
  count(DistrictName) %>%
  left_join(
    MSID %>% distinct(DISTRICT, DISTRICT_NAME),
    by = c("DistrictName" = "DISTRICT_NAME")
  ) %>%
  ungroup()

return(lost_kids_data)
})


datalist_processed <- purrr::pmap(
  list(data_list, eligiblity_list, all_students_list,lost_kids),
  function(x, y, z, a) {

    # ---- CLEAN ENROLLED ----
    nwri_enrolled <- x %>%
      filter(!is.na(MappedDOESchool)) %>%
      mutate(across(where(is.character), str_squish))
  

    # ---- CLEAN ELIGIBLE ----
    nwri_eligible <- y %>%
      mutate(across(where(is.character), str_squish)) %>%
      mutate(grade = str_remove(grade, "^0+"))

    # ---- CLEAN ALL STUDENTS ----
    nwri_all <- z %>%
      mutate(across(where(is.character), str_squish)) %>%
      mutate(grade = str_remove(grade, "^0+"))

    # ---- COUNT DATASETS ----
    enrolled_students <- nwri_enrolled %>%
      group_by(DistrictID) %>%
      summarise(n_enrolled = n(), .groups = "drop")



    eligible_students <- nwri_eligible %>%
      filter(grade != "P") %>%
      group_by(district) %>%
      summarise(n_eligible = n(), .groups = "drop")

    all_students <- nwri_all %>%
      filter(grade != "P") %>%
      group_by(district) %>%
      summarise(n_total = n(), .groups = "drop")
    


    # ---- FINAL DF ----
    df <- all_students %>%
      left_join(eligible_students, by = "district") %>%
      left_join(enrolled_students, by = c("district" = "DistrictID")) %>%
      left_join(a, by =c("district" = "DISTRICT")) %>%
      left_join(
        MSID %>%
          select(DISTRICT, SCHOOL, DISTRICT_NAME, SCHOOL_NAME_LONG) %>%
          distinct(DISTRICT, DISTRICT_NAME),
        by = c("district" = "DISTRICT")
      ) %>%
      rename(n_unmatched=n)
    return(df)
  }
)



part2<-lapply(datalist_processed, function(x){
  
  
  data_calcs<-x |> mutate(n_enrolled = ifelse(is.na(n_enrolled), 0, n_enrolled),
         n_eligible = ifelse(is.na(n_eligible), 0, n_eligible),
          n_unmatched = ifelse(is.na(n_unmatched), 0, n_unmatched))  |>
  filter(!is.na(n_total)) |>
  mutate(perc_enroll = n_enrolled/n_total,
         perc_eligible = n_eligible/n_total,
         n_enroll_unmatchadd = n_enrolled + n_unmatched,
         perc_enroll_unmatch = (n_unmatched+n_enrolled)/n_total) |>
  filter(!perc_enroll > 1) |>
  rename(DistrictID = district)
  
return(data_calcs)
})




district_levelprePM1<-part2[[1]] |>
   drop_na(DISTRICT_NAME) %>%
  select(-c(n_total)) |>
    mutate(period = "prepm1")

district_levelpostPM1<-part2[[2]] |>
   drop_na(DISTRICT_NAME) %>%
  select(-c(n_total)) |>
    mutate(period = "postpm1")


table<-rbind(district_levelprePM1, district_levelpostPM1) |>
  pivot_wider(id_cols = DISTRICT_NAME,names_from = period,values_from = c(perc_eligible, n_eligible, n_enrolled,n_enroll_unmatchadd,perc_enroll, perc_enroll_unmatch)) |>
  rowwise() |>
  mutate(delta_eligibile_n = n_eligible_postpm1 - n_eligible_prepm1,
         delta_eligibile_perc = round(100*(perc_eligible_postpm1 - perc_eligible_prepm1),1),
         delta_enroll_n = (n_enrolled_postpm1 - n_enrolled_prepm1),
         delta_enroll_n_unmatch = n_enroll_unmatchadd_postpm1 - n_enroll_unmatchadd_prepm1, 
         delta_enroll_perc = round(100*((perc_enroll_postpm1 - perc_enroll_prepm1)),1),
         delta_enroll_perc_unmatch = round(100*(perc_enroll_unmatch_postpm1 -
           perc_enroll_unmatch_prepm1),1)) |>
  mutate(diff_unmatch = round((delta_enroll_perc_unmatch-delta_enroll_perc ),1)) |>
  select(DISTRICT_NAME, delta_eligibile_n,delta_eligibile_perc,delta_enroll_n,delta_enroll_n_unmatch,delta_enroll_perc,diff_unmatch)



```



```{r, echo=FALSE, include=TRUE, warning=FALSE, cache=FALSE, message=FALSE}

font_size = 15
font_color = "#aaaaaa"
header_font_size = 16
header_font_color = "#97999b"
cell_padding = 6
centered = FALSE
#now create a theme for the table
slate_change<-function (font_size = 15, font_color = "#aaaaaa", header_font_size = 16, 
    header_font_color = "#97999b", cell_padding = 6, centered = FALSE, backcolor = "#272b30",
    borderColor2 = "#272b30") 
{
    if (!is.logical(centered)) {
        stop("`centered` must be TRUE or FALSE")
    }
    if (centered == TRUE) {
        centered_content = list(display = "flex", flexDirection = "column", 
            justifyContent = "center")
    }
    else {
        centered_content = NULL
    }
    reactableTheme(cellStyle = centered_content, color = font_color, 
        backgroundColor = backcolor, borderColor = borderColor2, 
        borderWidth = "1px", stripedColor = "#464a4d", highlightColor = "#464a4d", 
        cellPadding = cell_padding, tableStyle = list(fontSize = font_size), 
        headerStyle = list(borderWidth = "2px", backgroundColor = backcolor, 
            color = header_font_color, transitionDuration = "0.5s", 
            `&:hover[aria-sort]` = list(backgroundColor = "#141516", 
                color = "#ffffff"), `&[aria-sort='ascending'], &[aria-sort='descending']` = list(backgroundColor = "#141516", 
                color = "#ffffff"), fontSize = header_font_size), 
        groupHeaderStyle = list(`&:not(:empty)` = list(color = font_color, 
            fontSize = header_font_size), `&:hover` = list(fontWeight = "bold", 
            transitionDuration = "1s", transitionTimingFunction = "ease-out", 
            color = "#ffffff")), searchInputStyle = list(backgroundColor = "#ffffff", 
            color = "#aaaaaa", borderColor = "#dfe3e7", `&:focus` = list(color = "#aaaaaa")), 
        inputStyle = list(backgroundColor = "#ffffff", color = "#aaaaaa"), 
        rowSelectedStyle = list(backgroundColor = "#181a1c", 
            color = "#ffffff"), selectStyle = list(backgroundColor = "#41464c", 
            color = "#ffffff", borderColor = "#ffffff", outlineColor = "#ffffff", 
            `&:hover` = list(backgroundColor = "#17191b", color = "#ffffff")), 
        pageButtonStyle = list(backgroundColor = "#41464c", color = "#ffffff", 
            `&:hover` = list(backgroundColor = "#17191b", color = "#ffffff")), 
        pageButtonHoverStyle = list(backgroundColor = "#17191b", 
            color = "#ffffff"), pageButtonActiveStyle = list(backgroundColor = "#17191b", 
            color = "#ffffff"), pageButtonCurrentStyle = list(backgroundColor = "#17191b", 
            color = "#ffffff"))
}
tbl <- reactable(
  # General table options
  wrap = TRUE,
  defaultPageSize = 100,
  defaultSorted = 'delta_enroll_n',
  defaultSortOrder = "desc",
  highlight = TRUE,
  table,
  theme = slate_change(centered = TRUE, header_font_size = 20, font_size = 20),
  columns = list(
      DISTRICT_NAME = colDef( maxWidth = 220,
      name = "DISTRICT NAME",
      searchable = TRUE,
      filterable = TRUE),
    
    delta_enroll_perc = colDef(
      html = T, 
      align = "center",
      name = "Change Enrolled<br>(Percent Points)",
      cell = data_bars(
        data = table,
        fill_color = wes_palette("Zissou1", 100, type = "continuous"),
        background = "#272b30",
        bar_height = 7,
        text_position = 'outside-end',
        text_color = "cyan",
        round_edges = TRUE      )
    ),
    
    delta_eligibile_n = colDef(maxWidth = 200,
      align = "center",
      name = "Eligibility Change",
      cell = color_tiles(
        bold_text = TRUE,
        opacity = 0.7,
        brighten_text = FALSE,
        text_color = "white",
        data = table,
        number_fmt = scales::comma
      ),
      format = colFormat(separators = TRUE)
      ),
    
     delta_enroll_n_unmatch = colDef(maxWidth = 200,
                                     html =T,
      align = "center",
      name = "Enrollment Change<br>w/ Unmatched",
      cell = color_tiles(
        bold_text = TRUE,
        opacity = 0.7,
        brighten_text = FALSE,
        text_color = "white",
        data = table,
        number_fmt = scales::comma
      ),
      format = colFormat(separators = TRUE)
      ),
    
     delta_enroll_n = colDef(maxWidth = 200,
      align = "center",
      name = "Enrollment Change",
      cell = color_tiles(
        bold_text = TRUE,
        opacity = 0.7,
        brighten_text = FALSE,
        text_color = "white",
        data = table,
        number_fmt = scales::comma
      ),
      format = colFormat(separators = TRUE)
      ),
      
    
     diff_unmatch = colDef(
       html =T,
      align = "center",
      name = "Impact of Unmatched",
      cell = data_bars(
        data = table,
        fill_color = c("#1efffd"),
        background = "#272b30",
        bar_height = 7,
        text_position = 'outside-end',
        text_color = "cyan",
        round_edges = TRUE      )
    ),
    
    
    delta_eligibile_perc = colDef(html = T,
      align = "center",
      name = "Eligibility Change<br>(Percent Points)",
      headerStyle = list(whiteSpace = "normal"),
      cell = data_bars(
        data = table,
        fill_color = wes_palette("Zissou1", 100, type = "continuous"),
        background = "#272b30",
        bar_height = 7,
        text_position = 'outside-end',
        text_color = "cyan",
        round_edges = TRUE      )

    )
  )#end of columns
  )
tbl

```
::::
