name: Weekly Dropbox Download

on:
  push:
    branches: [main]
  schedule:
    # Weekdays only (1–5 = Mon–Fri)

    # DST: March–November
    # 7 AM ET = 11:00 UTC
    - cron: '0 11 * 3-11 1-5'
    # 3 PM ET = 19:00 UTC
    - cron: '0 19 * 3-11 1-5'

    # Standard Time: Jan, Feb, Dec
    # 7 AM ET = 12:00 UTC
    - cron: '0 12 * 1,2,12 1-5'
    # 3 PM ET = 20:00 UTC
    - cron: '0 20 * 1,2,12 1-5'
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Python and Dropbox SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install dropbox

      - name: Run Python script
        run: python dropbox_api.py

      - name: Commit and push downloaded file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add reports/Eligiblity_table_2526/dropbox_data/
          git diff --cached --quiet || git commit -m "Add/update downloaded file from Dropbox"
          git push
